version: '3'
services:
  app:
    build: .
    command: npm start
    environment:
      ALLOW_CONNECT_FROM: http://localhost:3000
      CLIENT_ID: d18e792778aa4ead9f39789a7ff440c3
      REDIS_URL: redis://redis:6379
      PORT: '3001'
      REDIRECT_HOST: http://localhost:3001
    ports:
      - 3001:3001
    env_file:
      - .env
    
  redis:
    image: redis:7.2.3
