# fly.toml app configuration file generated for music-akinyele-api on 2023-12-09T20:57:56-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "music-akinyele-api"
primary_region = "yyz"

[build]
dockerfile = "Dockerfile"

[http_service]
internal_port = 5000
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ["app"]

[env]
ALLOW_CONNECT_FROM = "https://www.akinyele.ca,https://old-react.akinyele.ca,http://localhost:3000,https://new-akinyele-ca.vercel.app,https://new.akinyele.ca"
REDIRECT_HOST = "https://music-akinyele-api.fly.dev"

[[vm]]
cpu_kind = "shared"
cpus = 1
memory_mb = 1024
